services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mercadoexpress
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
